os:
  - linux
  - osx

language: r

r: 
  - oldrel
  - release
  - devel
  
cache: packages
Imports: ggplot2, gridExtra, plyr, survival, survey

r_packages:
  - covr

r_github_packages:
  - jinseob2kim/jskm
  - r-lib/pkgdown

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  target-branch: master
